### ISSUE TITLE
Add support for OpenShift

### ISSUE THREAD

**Issue by megian** [projectsyn/component-eventrouter#21]
## Context
The current component does mostly match the [deployment suggested by Red Hat](https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-eventrouter.html#cluster-logging-eventrouter-deploy_cluster-logging-eventrouter), with the exception of:
* SecurityContext / runasUser
* Image
* CPU Memory requests

Tasks:
* Make the securityContext of the container deployment configurable.
* Add the capability of set request (and limits).

## Alternatives
Write an own component, specific for OpenShift.

**Comment by fhochleitner** [comment]
A working example without project template can also be found here: https://github.com/gepaplexx/gp-helm-chart-development/tree/develop/infra/gp-cluster-logging-eventrouter

Very quick of the sourcecode suggests that the namespace the eventrouter is running is is not relevant: https://github.com/openshift/eventrouter
